# Generated by Django 3.1.1 on 2020-10-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200925_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['creation_date'], 'permissions': (('can_publish', 'Can publish new blogs'),)},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='Blog posted on 2020-10-01', max_length=30),
        ),
    ]
