# Generated by Django 3.1.1 on 2020-10-01 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201001_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['creation_date']},
        ),
    ]
